### ISSUE TITLE
Omx player WebGui  

### ISSUE THREAD

**Issue by MarcoYepix** [brainfoolong/omxwebgui#2]
Hello BrainFooLong,
I ask You for help in this regard of omxplayer web gui, I have a problem in selecting the file, when I select the video, the status tells me video loading and after a few seconds says "video is not selected," you have no idea what could be the problem?
Also taking advantage of your kindness you can add the option to loop?

Thanks! for your attention!

**Comment by brainfoolong** [comment]
Hi, how you are using this application? With this `sudo apt-get install php5-cli` installed?
Have you tried any of this troubleshooting points https://github.com/brainfoolong/omxwebgui/blob/master/README.md#troubleshooting
In most situations this happens when the player could not start the video for some reason, this could have many reasons. Player blocked, video not supported, hdmi video device busy, etc..
For the point of "loop" option, i'll think about it.

**Comment by MarcoYepix** [comment]
thanks,
I have installed and the permissions are 777 in my apache root directory / var / www / omx,
He watches himself considers the slowness of cable or DSL at home, my ip http: //95.236.8.118/omx, regarding the permits I also run sudo usermod -a -G video www-data, but seems to have no effect , ok I check again, however, if you implement the loop.
thanks a lot

Marco

**Comment by brainfoolong** [comment]
Ok, i see you use "apache" as the php interpreter. There some issues with the apache webserver. Try it with the php5-cli suggested way from the readme to run the app, this should work fine.

**Comment by MarcoYepix** [comment]
ok, I'll do the tests, and I will inform you immediately.
thanks

**Comment by MarcoYepix** [comment]
Hello,
I ran the tests, and the software works well with Apache, you can make some changes, how to insert the .mov file selection, and the loop?
thanks
Marco

**Comment by brainfoolong** [comment]
I'll do some of the changes soon :) I close this issue.
